apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: aitask
spec:
  replicas: 3   # Scale this up for higher throughput
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: worker
          image: adityas23100/aitask-worker:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: aitask-config
            - secretRef:
                name: aitask-secret
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
